spring:
  cloud:
    gateway:
      routes:
        - id: nexus-test
          uri: http://127.0.0.1:9010 # 인증 서버 URI
          predicates: # 요청 헤더나 Path 조건 비교
            - Path=/test/** # 요청 Path
          filters:
            - AuthorizationHeaderFilter # JWT 검증을 위한 Custom GatewayFilter

        - id: nexus-user
          uri: http://127.0.0.1:9000
          predicates:
            - Path=/auth/**
eureka:
  instance:
    preferIpAddress: true
    lease-renewal-interval-in-seconds: 30
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://127.0.0.1:18001/eureka/
