server:
  port: 18010

spring:
  application:
    name: auth_token
  datasource:
    url: "jdbc:mysql://14.35.246.224:3306/gcumall?createDatabaseIfNotExist=true"
    username: admin
    password: 1210
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql # 추가 해준 부분
    #database-platform: org.hibernate.dialect.MySQL5InnoDBDialect # 추가 해준 부분
    show-sql: true

    hibernate:
      ddl-auto: update
    generate-ddl: true

    properties:
      dialect:
        #org.hibernate.dialect.MySQL5InnoDBDialect
      hibernate:
        format_sql: true

handlebars:
  suffix: .html
  expose-session-attribute: true

eureka:
  instance:
    preferIpAddress: true
    lease-renewal-interval-in-seconds: 30
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://172.30.1.65:18001/eureka/
