name: Deploy_and build
    
on:
    push:
        branches: [ master ]
    workflow_dispatch:

jobs:
  deploy:
    name: Deploy then build
    runs-on: [ubuntu-latest]
    
    steps:
      - name: SSH Remote Commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_IP }}
          username: ${{ secrets.REMOTE_SSH_ID }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.REMOTE_PORT }}
          script: |
            cd ./nexus_drone_be
            git pull
            bash -c 'cd ./nexus_drone_eureka && chmod +x ./gradlew &&./gradlew bootJar && cd ../'
            bash -c 'cd ./nexus_drone_gateway && chmod +x ./gradlew && ./gradlew bootJar && cd ../'
            bash -c 'cd ./nexus_drone_auth && chmod +x ./gradlew && ./gradlew bootJar && cd ../'
            bash -c 'cd ./nexus_drone_notice && chmod +x ./gradlew && ./gradlew bootJar && cd ../'
            bash -c 'cd ./nexus_drone_user && chmod +x ./gradlew && ./gradlew bootJar && cd ../'
            bash -c 'cd ./nexus_drone_drone && chmod +x ./gradlew && ./gradlew bootJar && cd ../'
            
            #screen -S nexus_eureka  -X quit
            #screen -dms nexus_eureka bash -c 'cd ./nexus_drone_eureka && chmod +x ./gradlew &&./gradlew bootJar && cd ../'
            #screen -S nexus_gateway  -X quit
            #screen -dms nexus_gateway bash -c 'cd /nexus_drone_gateway && chmod +x ./gradlew && ./gradlew bootJar && cd ../'
            #screen -S nexus_auth  -X quit
            #screen -dms nexus_auth bash -c 'cd ./nexus_drone_auth && chmod +x ./gradlew && ./gradlew bootJar && cd ../'
            #screen -S nexus_notice  -X quit
            #screen -dms nexus_notice bash -c 'cd ./nexus_drone_notice && chmod +x ./gradlew && ./gradlew bootJar && cd ../'
            #screen -S nexus_user  -X quit
            #screen -dms nexus_user bash -c 'cd ./nexus_drone_user && chmod +x ./gradlew && ./gradlew bootJar && cd ../'
            #screen -S nexus_drone  -X quit
            #screen -dms nexus_drone bash -c 'cd ./nexus_drone_drone && chmod +x ./gradlew && ./gradlew bootJar && cd ../'
